<?php
/**
 * @copyright 2015 City of Bloomington, Indiana
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<div class="cob-pageOverview">
    <div class="cob-pageOverview-container">
        <div>
            <p><?= $this->_('pageOverview_address', 'messages'); ?></p>
        </div>
        <aside>
            <dl></dl>
            <dd><?= $this->_('aboutThisAddress'); ?></dd>
            <dd><?= $this->_('governmentLinks'); ?></dd>
            <dd><?= $this->_('votingInfo'); ?></dd>
        </aside>
    </div>
</div>
