<?php
use Blossom\Classes\View;
use Blossom\Classes\Url;
?>
<header class="cob-siteHeader">
    <div class="cob-siteHeader-container">
        <div class="region region-header-site">
            <div id="block-search-form" class="block block-search">
                <div class="content">
                    <form action="http://rogue.bloomington.in.gov/drupal2" method="post" id="search-block-form" accept-charset="UTF-8">
                        <div>
                            <div class="form-item form-type-textfield form-item-search-block-form">
                                <label for="edit-search-block-form--2">How can we help you today? </label>
                                <input title="Enter the terms you wish to search for." placeholder="Search Bloomington.in.gov" type="text" id="edit-search-block-form--2" name="search_block_form" value="" size="15" maxlength="128" class="form-text" />
                            </div>
                            <div class="form-actions form-wrapper" id="edit-actions">
                                <input type="submit" id="edit-submit" name="op" value="Search" class="form-submit" />
                            </div>
                            <input type="hidden" name="form_build_id" value="form-P53a_GlmwvSlPfq1Yw3UnfXhak1ci-vjgFaplZ6qrBw" />
                            <input type="hidden" name="form_id" value="search_block_form" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <nav>
            <div class="menuLauncher">Menu</div>
            <div class="menuLinks closed">
                <a href="/drupal2/residents">Residents</a>
                <a href="/drupal2/taxonomy/term/2">Business</a>
                <a href="/drupal2/taxonomy/term/13">Visitors</a>
                <a href="/drupal2/taxonomy/term/3">Students</a>
                <a href="/drupal2/taxonomy/term/4">Government</a>
            </div>
        </nav>

        <a href="/drupal2/" class="cob-siteHeader-logo" title="Home" rel="home" id="logo">
            <img src="http://rogue.bloomington.in.gov/drupal2/themes/cob/logo.svg" alt="City of Bloomington, Indiana" />
        </a>
    </div>
</header>
