<?php
/**
 * @copyright 2015 City of Bloomington, Indiana
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 */
?>
<header class="cob-pageHeader ">
    <?= $this->includeBlocks('pageHeader'); ?>
    <div class="cob-pageOverview">
        <div class="cob-pageOverview-container">
        <?= $this->includeBlocks('pageOverview'); ?>
        </div>
    </div>
</header>
