---
- hosts: "mycity"
  become: "yes"
  roles:
    - "City-of-Bloomington.php"

  tasks:
    - name: "Create directories"
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
        mode:  "u=rwX,g=rwXs,o=rX"
      with_items:
        - "{{ mycity_backup_path  }}"
        - "{{ mycity_site_home    }}"

    - name: "Extract release"
      ansible.builtin.unarchive:
        src: "{{ mycity_archive_path }}"
        dest:    '/srv/sites'
        creates: '/srv/sites/mycity'

    - name: "Update site_home"
      command: "rsync -rl /srv/sites/mycity/data/ {{ mycity_site_home }}/"

    - name: "Apache configuration"
      template:
        src:  "apache.conf"
        dest: "/etc/apache2/sites-enabled/conf.d/mycity.conf"
      notify: "apache_restart"

    - name: "Install site_config"
      template:
        src:  "{{ inventory_dir }}/group_vars/mycity/templates/site_config.php"
        dest: "{{ mycity_site_home }}/site_config.php"

    - name: "Update directory ownership"
      command: "chown -R www-data:staff {{ item }}"
      args:
        warn: "no"
      with_items:
        - "{{ mycity_install_path }}"
        - "{{ mycity_backup_path  }}"
        - "{{ mycity_site_home    }}"

    - name: "Update directory permission"
      command: "chmod -R u=rwX,g=rwX,o=rX {{ item }}"
      args:
        warn: "no"
      with_items:
        - "{{ mycity_install_path }}"
        - "{{ mycity_backup_path  }}"
        - "{{ mycity_site_home    }}"
...
