<?php
/**
 * @copyright 2015 City of Bloomington, Indiana
 * @license http://www.gnu.org/licenses/agpl.txt GNU/AGPL, see LICENSE.txt
 * @author Cliff Ingham <inghamn@bloomington.in.gov>
 * @param Address $this->address
 */
use Blossom\Classes\View;

?>
<div class="myCity-home-greeting">
    <p>My Bloomington provides local information related to a given street address. Enter your address to learn more about:</p>

    <ul>
        <li>City services available</li>
        <li>Elected officials</li>
        <li>Related GIS attributes and data sets</li>
    </ul>
</div>
